// SPDX-License-Identifier: MIT OR Apache-2.0
// Workload: declarative (identity pool with deterministic seeding)
//! Browser identity pool for adaptive anti-bot rotation (WS-26).
//!
//! Each [`IdentityProfile`] bundles a User-Agent string, its detected browser
//! family, the platform it claims, and a deterministic seed used to produce
//! structural header variations (order, Accept-Language, Sec-CH-UA-Arch).
//!
//! The [`IdentityPool`] owns a fixed set of 12 identities (4 families × 3
//! platforms) and exposes a [`IdentityPool::rotate_on_block`] method that
//! implements the 5-level adaptive cascade used by `search::execute_with_retry`.
//!
//! ## Why a separate module
//!
//! The legacy `http::select_user_agent` function picks one UA at startup and
//! reuses it for the entire session. That single identity profile is easy for
//! DuckDuckGo to classify after the first request. The pool rotates identities
//! on detected blocks (HTTP 202/403/429) so retries do not keep the same
//! profile.

use rand::rngs::StdRng;
use rand::seq::{IndexedRandom, SliceRandom};
use rand::{RngExt, SeedableRng};
use serde::{Deserialize, Serialize};

/// Re-export of the CLI identity-profile enum so callers of this module
/// do not need to depend on the `cli` module to look up a fixed identity.
/// v0.7.10 GAP-WS-60 fix.
pub use crate::cli::CliIdentityProfile;

/// Browser family claimed by the identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[non_exhaustive]
pub enum BrowserFamily {
    /// Google Chrome or Chromium derivatives (excluding Edge).
    Chrome,
    /// Mozilla Firefox.
    Firefox,
    /// Apple Safari (UA without `Chrome/` indicator).
    Safari,
    /// Microsoft Edge (Chromium-based, contains `Edg/`).
    Edge,
}

impl BrowserFamily {
    /// Returns the canonical English name for use in metrics and logs.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Chrome => "chrome",
            Self::Firefox => "firefox",
            Self::Safari => "safari",
            Self::Edge => "edge",
        }
    }
}

/// Operating system platform claimed by the identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[non_exhaustive]
pub enum Platform {
    /// Microsoft Windows.
    Windows,
    /// Apple macOS.
    MacOS,
    /// Linux.
    Linux,
}

impl Platform {
    /// Returns the canonical English name for use in metrics and logs.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Windows => "windows",
            Self::MacOS => "macos",
            Self::Linux => "linux",
        }
    }
}

/// One selectable identity in the pool.
///
/// Bundles the User-Agent string with its detected family, the platform it
/// claims (used to drive Client Hints), and a deterministic seed that drives
/// the header order / Accept-Language / Sec-CH-UA variations generated by
/// [`IdentityProfile::shuffled_headers`].
#[derive(Debug, Clone)]
pub struct IdentityProfile {
    /// Detected browser family.
    pub family: BrowserFamily,
    /// Claimed platform.
    pub platform: Platform,
    /// Full User-Agent string.
    pub user_agent: String,
    /// Major version extracted from the UA (e.g. `146` for `Chrome/146`).
    pub major_version: u32,
    /// Normalized platform string for Client Hints (`"Windows"`, `"macOS"`, `"Linux"`).
    pub ua_platform: &'static str,
    /// Deterministic seed for header variation.
    pub seed: u64,
}

impl IdentityProfile {
    /// Produces a header set with family-specific content and
    /// seed-deterministic structural variation (order, Accept-Language, Sec-CH-UA-Arch).
    ///
    /// Returns a vector of `(name, value)` pairs ready to be inserted into
    /// a `reqwest::header::HeaderMap`.
    pub fn shuffled_headers(&self, language: &str, country: &str) -> Vec<(&'static str, String)> {
        let mut rng = StdRng::seed_from_u64(self.seed);
        let accept = self.accept_header();
        let accept_language = self.accept_language(language, country, &mut rng);
        // Only encodings the binary can decode (matches http::ACCEPT_ENCODING_SUPPORTED).
        let accept_encoding = "gzip, deflate".to_string();
        let platform_arc = self.platform_arch(&mut rng);

        // Headers emitted by every browser.
        let mut all: Vec<(&'static str, String)> = vec![
            ("accept", accept),
            ("accept-language", accept_language),
            ("accept-encoding", accept_encoding),
            ("upgrade-insecure-requests", "1".to_string()),
            ("sec-fetch-dest", "document".to_string()),
            ("sec-fetch-mode", "navigate".to_string()),
            ("sec-fetch-site", "none".to_string()),
            ("sec-fetch-user", "?1".to_string()),
        ];

        // Client Hints — only Chrome/Edge.
        if matches!(self.family, BrowserFamily::Chrome | BrowserFamily::Edge) {
            let sec_ch_ua = match self.family {
                BrowserFamily::Edge => format!(
                    r#""Chromium";v="{v}", "Microsoft Edge";v="{v}", "Not-A.Brand";v="99""#,
                    v = self.major_version
                ),
                _ => format!(
                    r#""Chromium";v="{v}", "Google Chrome";v="{v}", "Not-A.Brand";v="99""#,
                    v = self.major_version
                ),
            };
            let platform_quoted = format!(r#""{}""#, self.ua_platform);
            all.push(("sec-ch-ua", sec_ch_ua));
            all.push(("sec-ch-ua-mobile", "?0".to_string()));
            all.push(("sec-ch-ua-platform", platform_quoted));
            all.push(("sec-ch-ua-arch", platform_arc));
            all.push(("cache-control", "max-age=0".to_string()));
        }

        // Shuffle the order to mimic the (slightly) different order each
        // browser emits. Stable sort keeps the most important headers
        // (Accept, Accept-Language) in a position close to the top.
        all.shuffle(&mut rng);

        all
    }

    fn accept_header(&self) -> String {
        match self.family {
            BrowserFamily::Chrome | BrowserFamily::Edge => {
                "text/html,application/xhtml+xml,application/xml;q=0.9,\
                 image/avif,image/webp,image/apng,*/*;q=0.8"
            }
            BrowserFamily::Firefox => {
                "text/html,application/xhtml+xml,application/xml;q=0.9,\
                 image/avif,image/webp,*/*;q=0.8"
            }
            BrowserFamily::Safari => {
                "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
            }
        }
        .to_string()
    }

    fn accept_language(&self, language: &str, country: &str, rng: &mut StdRng) -> String {
        let lang = language.to_ascii_lowercase();
        let ctry = country.to_ascii_uppercase();
        // Deterministic 0/1 choose between the two real-world variants.
        let variant: u8 = rng.random_range(0..=1);
        if lang == "en" {
            match variant {
                0 => "en-US,en;q=0.9".to_string(),
                _ => "en-US,en;q=0.9,en-GB;q=0.8".to_string(),
            }
        } else {
            match variant {
                0 => format!("{lang}-{ctry},{lang};q=0.9,en-US;q=0.8,en;q=0.7"),
                _ => format!("{lang}-{ctry},{lang};q=0.9,en;q=0.8"),
            }
        }
    }

    fn platform_arch(&self, rng: &mut StdRng) -> String {
        // Chrome emits a Sec-CH-UA-Arch hint most of the time; we randomize
        // between x86, x86_64 and absent (each real-browser distribution).
        if rng.random_bool(0.85) {
            "x86_64".to_string()
        } else if rng.random_bool(0.5) {
            "x86".to_string()
        } else {
            String::new()
        }
    }

    /// Short identifier for the identity, suitable for the JSON metadata
    /// `identidade_usada` field. Format: `<family>-<platform>-<seed16hex>`.
    pub fn tag(&self) -> String {
        format!(
            "{}-{}-{:016x}",
            self.family.as_str(),
            self.platform.as_str(),
            self.seed
        )
    }
}

/// Pool of 12 identities (4 families × 3 platforms) used by the
/// adaptive anti-bot rotation in WS-26.
#[derive(Debug)]
pub struct IdentityPool {
    identities: Vec<IdentityProfile>,
    rng: StdRng,
    /// Cascade level (0 = current identity, 1+ = rotated).
    level: u32,
    /// Index of the identity currently in use.
    current: usize,
}

impl IdentityPool {
    /// Builds a pool of 12 identities from the built-in catalog.
    ///
    /// When `seed` is `Some`, the rotation order is fully deterministic.
    /// When `seed` is `None`, a random seed is drawn from the OS RNG.
    pub fn new(seed: Option<u64>) -> Self {
        let identities = build_default_identities();
        let s = seed.unwrap_or_else(|| {
            let mut r = rand::rng();
            r.random::<u64>()
        });
        let rng = StdRng::seed_from_u64(s);
        Self {
            identities,
            rng,
            level: 0,
            current: 0,
        }
    }

    /// Returns the identity currently in use.
    pub fn current(&self) -> &IdentityProfile {
        &self.identities[self.current]
    }

    /// Current cascade level (0 = first attempt, 1+ = rotated).
    pub fn level(&self) -> u32 {
        self.level
    }

    /// Resets the cascade to the first attempt (used at the start of a new query).
    pub fn reset(&mut self) {
        self.level = 0;
    }

    /// Iterates over all identities in the pool in catalog order. Public
    /// API for callers that need to look up a specific identity by
    /// family+platform (e.g. the `--identity-profile` flag in
    /// `pipeline::execute_single_search`). v0.7.10 GAP-WS-60.
    pub fn iter(&self) -> std::slice::Iter<'_, IdentityProfile> {
        self.identities.iter()
    }

    /// Pins the current identity to the given index and resets the cascade
    /// level to 0. Used to fix the session to a specific identity. No-op
    /// when the index is out of bounds. v0.7.10 GAP-WS-60.
    pub fn pin_to(&mut self, index: usize) {
        if index < self.identities.len() {
            self.current = index;
            self.level = 0;
        }
    }

    /// Returns the index of the first identity whose `family` and `platform`
    /// match the given pair. Returns `None` if no match exists in the
    /// catalog (should not happen given the 4×3=12 built-in identities).
    /// v0.7.10 GAP-WS-60.
    pub fn find_index(&self, family: BrowserFamily, platform: Platform) -> Option<usize> {
        self.identities
            .iter()
            .position(|p| p.family == family && p.platform == platform)
    }

    /// Returns the identity at the given index. Public read-only API for
    /// callers that need to inspect a specific identity. v0.7.10 GAP-WS-60.
    pub fn get(&self, index: usize) -> Option<&IdentityProfile> {
        self.identities.get(index)
    }

    /// Returns the index of the currently-active identity. Public API for
    /// tests and for callers that want to read the current pin without
    /// consuming the `&IdentityProfile` borrow. v0.7.10 GAP-WS-60.
    pub fn current_index(&self) -> usize {
        self.current
    }

    /// Advances the cascade and returns the new active identity.
    ///
    /// Cascade strategy (5 levels, used by `search::execute_with_retry`):
    /// 0. Current identity (no rotation).
    /// 1. Same family, different platform.
    /// 2. Different family, same platform.
    /// 3. Different family and platform + endpoint will be downgraded to lite.
    /// 4. Random identity (caller should sleep 30-60s before retrying).
    pub fn rotate_on_block(&mut self) -> &IdentityProfile {
        self.level = self.level.saturating_add(1);
        let next = match self.level {
            1 => self.pick_same_family_different_platform(),
            2 => self.pick_different_family_same_platform(),
            3 => self.pick_different_family_and_platform(),
            4.. => self.pick_random(),
            _ => self.current,
        };
        self.current = next;
        &self.identities[self.current]
    }

    /// Returns the `identidade_usada` string for the active identity.
    pub fn active_tag(&self) -> String {
        self.current().tag()
    }

    fn pick_same_family_different_platform(&mut self) -> usize {
        let current = &self.identities[self.current];
        let candidates: Vec<usize> = self
            .identities
            .iter()
            .enumerate()
            .filter(|(i, p)| *i != self.current && p.family == current.family)
            .map(|(i, _)| i)
            .collect();
        self.choose_from(&candidates)
    }

    fn pick_different_family_same_platform(&mut self) -> usize {
        let current = &self.identities[self.current];
        let candidates: Vec<usize> = self
            .identities
            .iter()
            .enumerate()
            .filter(|(i, p)| *i != self.current && p.platform == current.platform)
            .map(|(i, _)| i)
            .collect();
        self.choose_from(&candidates)
    }

    fn pick_different_family_and_platform(&mut self) -> usize {
        let current = &self.identities[self.current];
        let candidates: Vec<usize> = self
            .identities
            .iter()
            .enumerate()
            .filter(|(i, p)| {
                *i != self.current && p.family != current.family && p.platform != current.platform
            })
            .map(|(i, _)| i)
            .collect();
        self.choose_from(&candidates)
    }

    fn pick_random(&mut self) -> usize {
        let n = self.identities.len();
        self.rng.random_range(0..n)
    }

    fn choose_from(&mut self, candidates: &[usize]) -> usize {
        if candidates.is_empty() {
            return self.pick_random();
        }
        candidates
            .choose(&mut self.rng)
            .copied()
            .unwrap_or(self.current)
    }
}

/// Resolves a [`CliIdentityProfile`] to a concrete [`crate::http::BrowserProfile`] derived
/// from the 12-identity catalog. Returns `None` when the CLI profile is
/// `Auto` (caller should use the default profile in that case).
///
/// `seed` controls the rotation order in the underlying pool (matches the
/// `IdentityPool::new(seed)` convention). When `None`, the pool uses a
/// random OS-derived seed.
///
/// v0.7.10 GAP-WS-60 fix — `--identity-profile` was previously declared
/// on the CLI but never propagated to the pipeline. This helper is the
/// single integration point.
pub fn browser_profile_for_cli_identity(
    cli: CliIdentityProfile,
    seed: Option<u64>,
) -> Option<crate::http::BrowserProfile> {
    let (target_family, target_platform) = cli.family_and_platform()?;
    let mut pool = IdentityPool::new(seed);
    let idx = pool.find_index(target_family, target_platform).unwrap_or(0);
    pool.pin_to(idx);
    let ua = pool.current().user_agent.clone();
    Some(crate::http::create_browser_profile(&ua))
}

/// Returns the canonical identity tag (e.g. `chrome-linux-33333333cccc0003`)
/// for the given CLI identity profile, or `None` when `cli` is `Auto`.
///
/// v0.7.10 GAP-AUD-001 fix — failure paths (`parallel::error_output`,
/// `pipeline::failure_output`) need the same identity tag the success
/// path reports, so the caller can correlate a failure to a specific
/// identity in the 12-identity pool. Reuses `IdentityProfile::tag()`
/// to guarantee format parity with the success path.
pub fn identity_tag_for_cli_identity(cli: CliIdentityProfile, seed: Option<u64>) -> Option<String> {
    let (target_family, target_platform) = cli.family_and_platform()?;
    let mut pool = IdentityPool::new(seed);
    let idx = pool.find_index(target_family, target_platform).unwrap_or(0);
    pool.pin_to(idx);
    Some(pool.current().tag())
}

/// Returns the User-Agent string for the current identity selection.
/// Used by Chrome headless to set `--user-agent` flag matching the identity pool.
///
/// When `cli` is `Auto`, returns the first identity's UA (deterministic per seed).
/// When pinned, returns the specific identity's UA.
pub fn current_user_agent_for_chrome(cli: CliIdentityProfile, seed: Option<u64>) -> String {
    match browser_profile_for_cli_identity(cli, seed) {
        Some(profile) => profile.user_agent,
        None => {
            let pool = IdentityPool::new(seed);
            pool.current().user_agent.clone()
        }
    }
}

/// Reescreve a major version do Chrome no `user_agent` para `major` (GAP-WS-109 v0.9.2).
///
/// O pool de identidades possui UAs com `Chrome/146`, mas o Chrome real instalado
/// can be 149+. `navigator.userAgent` is overwritten by `--user-agent=`, however
/// Client Hints (`navigator.userAgentData.brands`, `sec-ch-ua`) ainda refletem a
/// real version — producing a detectable mismatch. This function aligns the UA to
/// version detected via `chrome --version`. Locates `Chrome/` followed by digits
/// and replaces the first numeric group with `major`. Returns the UA unchanged if
/// `Chrome/` is not found.
pub fn rewrite_ua_chrome_version(ua: &str, major: u32) -> String {
    let marker = "Chrome/";
    let Some(idx) = ua.find(marker) else {
        return ua.to_string();
    };
    let start = idx + marker.len();
    let digits_end = ua[start..]
        .find(|c: char| !c.is_ascii_digit())
        .map(|d| start + d)
        .unwrap_or(ua.len());
    let mut out = String::with_capacity(ua.len() + 4);
    out.push_str(&ua[..start]);
    out.push_str(&major.to_string());
    out.push_str(&ua[digits_end..]);
    out
}

/// Returns a Chrome UA string matching the current platform.
/// Used by the Chrome-primary search path so UA family matches the native
/// Chromium TLS stack (never pair Safari/Firefox UA with Chrome). GAP-WS-074.
pub fn chrome_only_ua_for_platform() -> String {
    let pool = IdentityPool::new(None);
    let target_platform = if cfg!(target_os = "windows") {
        Platform::Windows
    } else if cfg!(target_os = "macos") {
        Platform::MacOS
    } else {
        Platform::Linux
    };
    pool.iter()
        .find(|p| p.family == BrowserFamily::Chrome && p.platform == target_platform)
        .map(|p| p.user_agent.clone())
        .unwrap_or_else(|| {
            pool.iter()
                .find(|p| p.family == BrowserFamily::Chrome)
                .map(|p| p.user_agent.clone())
                .unwrap_or_else(|| "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36".to_string())
        })
}

/// Coerces a candidate UA to a Chrome/platform-correct string for chromiumoxide.
///
/// Safari/Firefox UAs must not be paired with the Chromium process TLS stack.
/// Wrong-platform Chrome UAs are rewritten. Shared by single-path and fan-out
/// (GAP-WS-AGENT-READY-001 L-07).
#[must_use]
pub fn coerce_chrome_user_agent(candidate: &str) -> String {
    if candidate.contains("Firefox/")
        || (candidate.contains("Safari/") && !candidate.contains("Chrome/"))
    {
        tracing::info!(
            original_ua = %candidate,
            "UA mismatch: Safari/Firefox UA with Chromium process — forcing Chrome UA"
        );
        return chrome_only_ua_for_platform();
    }
    if !ua_platform_matches_host(candidate) {
        tracing::info!(
            original_ua = %candidate,
            "UA platform mismatch with host — forcing platform-correct Chrome UA (GAP-WS-107b)"
        );
        return chrome_only_ua_for_platform();
    }
    candidate.to_string()
}

/// Effective Chrome identity after coerce + optional major rewrite.
///
/// Single source of truth for chromiumoxide launch UA **and** agent metadata
/// (`SearchMetadata.user_agent` / `identity_used`). Closes
/// GAP-E2E-V14-UA-METADATA-LIE / UA-MAJOR-SKEW (anti-CF rule 4).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EffectiveChromeIdentity {
    /// UA string passed to Chrome and emitted on the wire.
    pub user_agent: String,
    /// Stable pool tag for the host Chrome identity (seed-based, not fragile
    /// equality against the post-rewrite UA string).
    pub tag: String,
}

/// Host platform claimed by Chrome identities on this build target.
#[must_use]
pub fn host_chrome_platform() -> Platform {
    if cfg!(target_os = "windows") {
        Platform::Windows
    } else if cfg!(target_os = "macos") {
        Platform::MacOS
    } else {
        Platform::Linux
    }
}

/// Stable identity tag for the host Chrome pool entry (GAP-E2E-V14).
///
/// Prefer the pool's canonical `IdentityProfile::tag()` for Chrome+host OS so
/// agents keep the familiar `<family>-<platform>-<16hex>` shape. Do **not**
/// match on exact UA equality after major rewrite (that always misses).
#[must_use]
pub fn chrome_identity_tag_for_host() -> String {
    let target = host_chrome_platform();
    let pool = IdentityPool::new(None);
    pool.iter()
        .find(|p| p.family == BrowserFamily::Chrome && p.platform == target)
        .map(|p| p.tag())
        .unwrap_or_else(|| format!("chrome-{}-coerced", target.as_str()))
}

/// Resolve the effective Chrome identity: coerce family/platform, then align
/// major version when `host_major` is known.
///
/// # Arguments
///
/// * `candidate` — pool / pinned / CLI UA before Chrome launch
/// * `host_major` — parsed from `chrome --version` when available; `None` skips rewrite
///
/// # Agent contract
///
/// Callers MUST emit `user_agent` and `tag` from the returned value on success
/// paths so launch ≡ wire (no Firefox/Safari/Mac-on-Linux lies).
#[must_use]
pub fn resolve_effective_chrome_identity(
    candidate: &str,
    host_major: Option<u32>,
) -> EffectiveChromeIdentity {
    let coerced = coerce_chrome_user_agent(candidate);
    let user_agent = match host_major {
        Some(major) => rewrite_ua_chrome_version(&coerced, major),
        None => coerced,
    };
    EffectiveChromeIdentity {
        user_agent,
        tag: chrome_identity_tag_for_host(),
    }
}

/// Retorna `true` quando o UA afirma o mesmo SO do host compilado (GAP-WS-107b v0.9.1).
/// Used to force platform coercion when the pool selects a Chrome UA from the
/// wrong OS (e.g. chrome-windows on a macOS host) — keeps UA platform aligned
/// with the host and Client Hints (GraphRAG: do not mix UA platform with TLS stack).
pub fn ua_platform_matches_host(ua: &str) -> bool {
    if cfg!(target_os = "windows") {
        ua.contains("Windows NT")
    } else if cfg!(target_os = "macos") {
        ua.contains("Macintosh") || ua.contains("Mac OS X")
    } else {
        ua.contains("X11; Linux") || ua.contains("Linux x86_64")
    }
}

fn build_default_identities() -> Vec<IdentityProfile> {
    // 4 families × 3 platforms = 12 identities.
    // Each UA string is paired with its family and platform metadata.
    // The seed is derived from a hash of the UA so the same UA produces
    // the same header order across runs.
    vec![
        IdentityProfile {
            family: BrowserFamily::Chrome,
            platform: Platform::Windows,
            user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36".into(),
            major_version: 146,
            ua_platform: "Windows",
            seed: 0x1111_1111_aaaa_0001,
        },
        IdentityProfile {
            family: BrowserFamily::Chrome,
            platform: Platform::MacOS,
            user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36".into(),
            major_version: 146,
            ua_platform: "macOS",
            seed: 0x2222_2222_bbbb_0002,
        },
        IdentityProfile {
            family: BrowserFamily::Chrome,
            platform: Platform::Linux,
            user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36".into(),
            major_version: 146,
            ua_platform: "Linux",
            seed: 0x3333_3333_cccc_0003,
        },
        IdentityProfile {
            family: BrowserFamily::Edge,
            platform: Platform::Windows,
            user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 Edg/145.0.3800.97".into(),
            major_version: 145,
            ua_platform: "Windows",
            seed: 0x4444_4444_dddd_0004,
        },
        IdentityProfile {
            family: BrowserFamily::Edge,
            platform: Platform::MacOS,
            user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 Edg/145.0.3800.97".into(),
            major_version: 145,
            ua_platform: "macOS",
            seed: 0x5555_5555_eeee_0005,
        },
        IdentityProfile {
            family: BrowserFamily::Edge,
            platform: Platform::Linux,
            user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 Edg/145.0.3800.97".into(),
            major_version: 145,
            ua_platform: "Linux",
            seed: 0x6666_6666_ffff_0006,
        },
        IdentityProfile {
            family: BrowserFamily::Firefox,
            platform: Platform::Windows,
            user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0".into(),
            major_version: 134,
            ua_platform: "Windows",
            seed: 0x7777_7777_aaaa_0007,
        },
        IdentityProfile {
            family: BrowserFamily::Firefox,
            platform: Platform::MacOS,
            user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 14.6; rv:134.0) Gecko/20100101 Firefox/134.0".into(),
            major_version: 134,
            ua_platform: "macOS",
            seed: 0x8888_8888_bbbb_0008,
        },
        IdentityProfile {
            family: BrowserFamily::Firefox,
            platform: Platform::Linux,
            user_agent: "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0".into(),
            major_version: 134,
            ua_platform: "Linux",
            seed: 0x9999_9999_cccc_0009,
        },
        IdentityProfile {
            family: BrowserFamily::Safari,
            platform: Platform::Windows,
            user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15".into(),
            major_version: 17,
            ua_platform: "Windows",
            seed: 0xaaaa_aaaa_dddd_000a,
        },
        IdentityProfile {
            family: BrowserFamily::Safari,
            platform: Platform::MacOS,
            user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15".into(),
            major_version: 17,
            ua_platform: "macOS",
            seed: 0xbbbb_bbbb_eeee_000b,
        },
        IdentityProfile {
            family: BrowserFamily::Safari,
            platform: Platform::Linux,
            user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15".into(),
            major_version: 17,
            ua_platform: "Linux",
            seed: 0xcccc_cccc_ffff_000c,
        },
    ]
}

/// Probe result reported by the `--probe` flag of the CLI.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProbeReport {
    /// Endpoint that was probed (`"html"` or `"lite"`).
    pub endpoint: String,
    /// HTTP status returned by DDG.
    pub status: u16,
    /// Round-trip latency in milliseconds.
    pub latency_ms: u64,
    /// Whether the response carried a `Set-Cookie` header.
    pub has_set_cookie: bool,
    /// Identity tag used for the probe.
    pub identity: String,
}


#[cfg(test)]
#[path = "identity_tests.rs"]
mod tests;
